{
  config.substrate.modules.programs.firefox = {
    tags = [ "gui" ];

    # Firefox profile generation replaces HM's programs.firefox: a static
    # profiles.ini pointing at the runtime-owned "default" dir, plus the
    # declarative files Firefox won't overwrite (user.js, chrome/, xpi
    # links). Firefox fills in the rest of the profile at runtime.
    perUser =
      { config, lib, pkgs, ... }:
      let
        profileDir = ".mozilla/firefox/default";
        appGuid = "{ec8030f7-c20a-464f-9b0e-13a3a9e97384}";

        settings = {
          "browser.disableResetPrompt" = true;
          "browser.newtabpage.activity-stream.showSponsoredTopSites" = false;
          "browser.shell.checkDefaultBrowser" = false;
          "browser.startup.homepage" = "https://www.raeford.wilsonfamilyhq.com/";
          "browser.toolbars.bookmarks.visibility" = "always";
          "privacy.trackingprotection.enabled" = true;
          "signon.rememberSignons" = false;
          "toolkit.legacyUserProfileCustomizations.stylesheets" = true;
          "trailhead.firstrun.didSeeAboutWelcome" = true;
        };

        prefValue =
          v:
          if lib.isBool v then
            (if v then "true" else "false")
          else if lib.isInt v then
            toString v
          else
            builtins.toJSON v;
        userJsLines = lib.mapAttrsToList (k: v: "user_pref(${builtins.toJSON k}, ${prefValue v});") settings;

        addons = with pkgs.nur.repos.rycee.firefox-addons; [
          multi-account-containers
          musescore-downloader
          onepassword-password-manager
          sidebery
          temporary-containers
          user-agent-string-switcher
        ];
        extensionFiles = lib.listToAttrs (
          map (
            drv:
            {
              name = "${profileDir}/extensions/${drv.passthru.addonId}.xpi";
              value.source = "${drv}/share/mozilla/extensions/${appGuid}/${drv.passthru.addonId}.xpi";
            }
          ) addons
        );
      in
      {
        packages = [ pkgs.firefox ];

        hdwlinux.app.webBrowser = lib.mkDefault {
          package = pkgs.firefox;
          desktopName = "firefox.desktop";
        };

        hdwlinux.programs.browserctl.browsers.firefox = "firefox.desktop";

        files = extensionFiles // {
          ".mozilla/firefox/profiles.ini".text = ''
            [General]
            StartWithLastProfile=1
            Version=2

            [Profile0]
            Default=1
            IsRelative=1
            Name=default
            Path=default
          '';

          "${profileDir}/user.js".text = "// Generated by hdwlinux perUser.\n\n\n\n" + lib.concatStringsSep "\n" userJsLines + "\n\n\n\n";

          "${profileDir}/chrome/userChrome.css".text = ''
            #main-window .toolbar-items {
              overflow: hidden;
              transition: height 0.3s 0.3s !important;
            }
            #main-window .toolbar-items { height: 3em !important; }
            #main-window[uidensity="touch"] .toolbar-items { height: 3.35em !important; }
            #main-window[uidensity="compact"] .toolbar-items { height: 2.7em !important; }
            #main-window[titlepreface*="XXX"] .toolbar-items { height: 0 !important; }
            #main-window[titlepreface*="XXX"] #tabbrowser-tabs { z-index: 0 !important; }
          '';
        };
      };
  };
}
