/**
 * Validation utilities module
 */

export { validateClient, validateClientOrThrow, ClientValidationError } from "./client-validator.js"
export {
  validateProjectId,
  validateIssueId,
  sanitizePathComponent,
  createSafeWorktreeName,
  validatePathBoundary,
  type PathValidationError,
} from "./path-validator.js"
export {
  InputValidationError,
  ProjectNameSchema,
  ProjectIdSchema,
  OptionalProjectIdSchema,
  IssueIdSchema,
  OptionalIssueIdSchema,
  IssueTitleSchema,
  IssueDescriptionSchema,
  PrioritySchema,
  LabelSchema,
  LabelsSchema,
  BlockedBySchema,
  WorkspacePathSchema,
  TimeoutMsSchema,
  DelegationIdSchema,
  AgentNameSchema,
  AgentsSchema,
  AlternativeSchema,
  ArtifactTypeSchema,
  ArtifactPathSchema,
  ProjectCreateArgsSchema,
  ProjectFocusArgsSchema,
  ProjectCloseArgsSchema,
  ProjectListArgsSchema,
  ProjectStatusArgsSchema,
  ProjectCreateIssueArgsSchema,
  ProjectUpdateIssueArgsSchema,
  ProjectWorkOnIssueArgsSchema,
  ProjectDelegationReadArgsSchema,
  ProjectPlanArgsSchema,
  ProjectRecordDecisionArgsSchema,
  ProjectSaveArtifactArgsSchema,
  validateInput,
  validateToolArgs,
  formatValidationError,
  type ProjectCreateArgs,
  type ProjectFocusArgs,
  type ProjectCloseArgs,
  type ProjectListArgs,
  type ProjectStatusArgs,
  type ProjectCreateIssueArgs,
  type ProjectUpdateIssueArgs,
  type ProjectWorkOnIssueArgs,
  type ProjectDelegationReadArgs,
  type ProjectPlanArgs,
  type ProjectRecordDecisionArgs,
  type ProjectSaveArtifactArgs,
} from "./input-schemas.js"
