prSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me -author:@me
  - title: Involved
    filters: is:open involves:@me -review-requested:@me -author:@me -repo:mongodb/mongo-csharp-driver -repo:bdeleonardis1/parquet-go
  - title: mongohouse
    filters: is:open repo:10gen/mongohouse -author:@me -review-requested:@me -involves:@me
    limit: 50 # optional limit per section
  - title: mongoast
    filters: is:open repo:10gen/mongoast -author:@me -review-requested:@me -involves:@me
  - title: bsonutil
    filters: is:open repo:10gen/bsonutil -author:@me -review-requested:@me -involves:@me
  - title: bsonio
    filters: is:open repo:10gen/bsonio -author:@me -review-requested:@me -involves:@me
issuesSections:

defaults:
  prsLimit: 20 # global limit
  issuesLimit: 20 # global limit
  preview:
    open: true
    width: 60
repoPaths:
  10gen/*: /home/craig/Projects/github.com/10gen/*
  craiggwilson/*: /home/craig/Projects/github.com/craiggwilson/*
