[[keys]]
    index = 0
    [keys.widget]
        id = "button"
        [keys.widget.config]
            icon = "assets/App-OBS.png"
    [keys.action]
        deck = "obs.toml"

[[keys]]
    index = 4
    [keys.widget]
        id = "button"
        [keys.widget.config]
            icon = "assets/Stream-On.png"
    [keys.action]
        deck = "vpn.toml"

[[keys]]
    index = 10
    [keys.widget]
        id = "button"
        [keys.widget.config]
            icon = "assets/App-Pihole-On.png"
    [keys.action]
        exec = "curl -ks https://pihole.raeford.wilsonfamilyhq.com/admin/api.php?enable&auth=892f0036c6e55f9739a8844c77ffdc437f0bdece331cb31bed0cfb0a093a919c"

[[keys]]
    index = 11
    [keys.widget]
        id = "button"
        [keys.widget.config]
            icon = "assets/App-Pihole-Off.png"
    [keys.action]
        exec = "curl -ks https://pihole.raeford.wilsonfamilyhq.com/admin/api.php?disable&auth=892f0036c6e55f9739a8844c77ffdc437f0bdece331cb31bed0cfb0a093a919c"

[[keys]]
    index = 13
    [keys.widget]
        id = "top"
        [keys.widget.config]
            mode = "cpu"
            fillColor = "#d497de"

[[keys]]
    index = 14
    [keys.widget]
        id = "top"
        [keys.widget.config]
            mode = "memory"
            fillColor = "#d497de"



