[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hdwlinux-fabric-shell"
version = "0.0.1"
requires-python = ">= 3.11"
authors = [
]
maintainers = [
]
description = "Shell for HDWLinux using Fabric."
readme = "README.md"
license = {file = "LICENSE"}

[project.scripts]
bar = "bar.bar:main"

[tool.setuptools]
packages = ["bar"]

[tool.setuptools.package-data]
bar = ["bar.css"]